---
title: "Palmer Penguins"
author: "mnaR99"
date: "28/7/2020"
output: html_document
---

```{r}
library(tidyverse)
library(ggbump)
library(extrafont)
library(cowplot)
```

```{r}
tuesdata <- tidytuesdayR::tt_load(2020, week = 31)

penguins <- tuesdata$penguins
```

```{r Flop Image}
library(magick)

img <- image_read("penguin.png")

image_write(image_flop(img), "penguin2.png", format = "png")
```

```{r Palette}
pal1 <- c("#FF8C01", "#A034F0", "#4CA4A4")
pal2 <- c(pal1, as.character(prismatic::clr_darken(pal1, shift = 0.3)))
pal2 <- pal2[c(1,4,2,5,3,6)]
```

```{r Plot data}
data <- penguins %>% 
  filter(!is.na(sex)) %>% 
  select(-year, -island) %>% 
  mutate(
    id = row_number(),
    sex = str_to_title(sex),
    comb = paste(species, sex),
    species = recode(species, "Adelie" = "Adélie")
  ) %>% 
  gather(variable, value, bill_length_mm:body_mass_g) %>% 
  mutate(
    variable = fct_relevel(variable, "flipper_length_mm","bill_length_mm","bill_depth_mm","body_mass_g"),
    variable = fct_relabel(variable, ~str_replace_all(., "_", " ") %>% 
                             str_replace("(.*) (.+)$", "\\1 (\\2)") %>% 
                             str_to_sentence())
  ) %>% 
  group_by(variable) %>% 
  mutate(
    st = (value-min(value))/(max(value)-min(value))
  )

summ_data <- data %>% 
  group_by(species, sex, comb, variable) %>% 
  summarise(
    stat = median(value),
    stat_st = median(st)
  )
```

```{r Plot}
plot <- ggplot() +
    aes(x = variable, color = comb, group = comb) +
    geom_bump(
      data = data,
      aes(y = st, group = id),
      size = 2,
      alpha = 0.07,
      lineend = "round"
    ) +
    geom_bump(
      data = summ_data,
      aes(y = stat_st),
      size = 2
    ) +
    geom_label(
      data = summ_data,
      aes(y = stat_st, fill = comb, label = stat),
      size = 5,
      color = "white",
      family = "Righteous",
      label.size = NA
    ) +
    scale_y_continuous(
      limits = c(0,1),
      breaks = c(0,1),
      labels = c("Min.", "Max."),
      sec.axis = dup_axis()
    ) +
    scale_x_discrete(
      position = "top"
    ) +
    facet_wrap(~species) +
    scale_color_manual(values = pal2) +
    scale_fill_manual(values = pal2) +
    labs(
      title = "Palmer Penguins",
      subtitle = "Median by sex of physical measures for the three different species of penguins in the Palmer Archipelago, Antarctica.",
      caption = "@AtMissing · Palmer Archipelago (Antarctica) penguin data by Gorman, Williams and Fraser, 2014"
    ) +
    theme(
      plot.title = element_text(
        family = "Righteous",
        size = 40,
        hjust = 0.5,
        margin = margin(t = 20, b = 5)
      ),
      plot.subtitle = element_text(
        hjust = 0.5,
        family = "Open Sans",
        margin = margin(t = 5, b = 10)
      ),
      plot.caption = element_text(
        hjust = 0.5,
        family = "Open Sans",
        margin = margin(t = 20, b = 10)
      ),
      strip.placement = "outside",
      strip.text = element_text(
        family = "Righteous",
        size = 20,
        color = "white"
      ),
      strip.background = element_rect(
        fill = "black"
      ),
      axis.text.x = element_text(
        family = "Open Sans"
      ),
      panel.background = element_rect(
        fill = "#ECEBE4"
      ),
      axis.title = element_blank(),
      axis.text.y = element_blank(),
      axis.ticks = element_blank(),
      panel.grid.minor = element_blank(),
      panel.grid.major = element_blank(),
      legend.position = "none"
    )

plot <- ggdraw() +
  draw_plot(plot) +
  draw_image("img/penguin.png", scale = 0.07, x = 0.13, y = 0.45) +
  draw_image("img/penguin2.png", scale = 0.07, x = -0.13, y = 0.45)
```

```{r}
ggsave(here::here("plots","wk_31_2020.pdf"), plot, width = 20, height = 10, device = cairo_pdf)

pdftools::pdf_convert(
  pdf = here::here("plots","wk_31_2020.pdf"),
  filenames = here::here("plots","wk_31_2020.png"),
  format = "png", 
  dpi = 400
)
```

